MODEL:
    NAME: "wide_resnet50_2"        # Change
    PRETRAINED: True        # Change
    BATCH_SIZE: 8
    N_CLASS: 2
    SAVE_TO: models
SOLVER:
    EPOCH: 7                # Change
    INIT_LR: 0.005
    MOMENTUM: 0.9
    WEIGHT_DECAY: 0.0005
SCHEDULER:
    IN_EVERY: [5]             # Change
    GAMMA: 0.1
RECORD:
    LOSS: True
    AUC: True
    FROC: True
AUGMENT:
    STATE: False
